image: git-ee.remondis-de.local:4567/renew/docker-images/node9.5.0-chrome

stages:
  - dependencies
  - publish

ui-download-dependencies:
  stage: dependencies
  tags:
    - docker
  script:
    - export http_proxy=http://remondis-de%5CDE9899-Proxy:PasswordSwordfish9899@proxy.remondis.local:80/
    - export https_proxy=http://remondis-de%5CDE9899-Proxy:PasswordSwordfish9899@proxy.remondis.local:80/
    - npm install
  artifacts:
    paths:
      - node_modules/*
    expire_in: 1 day
    when: on_success

publish-pacts:
  stage: publish
  script:
    - npm run publish:pacts
