image: git-ee.remondis-de.local:4567/renew/docker-images/node9.5.0-chrome

stages:
  - dependencies
  - publish

ui-download-dependencies:
  stage: dependencies
  tags:
    - docker
  script:
    - export http_proxy=$CI_HTTP_PROXY
    - export https_proxy=$CI_HTTPS_PROXY
    - npm install
  artifacts:
    paths:
      - node_modules/*
    expire_in: 1 day
    when: on_success

publish-pacts:
  stage: publish
  script:
    - npm run publish:pacts
